SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `lignes_inventaire`;
DROP TABLE IF EXISTS `inventaires_physiques`;
DROP TABLE IF EXISTS `lignes_commande`;
DROP TABLE IF EXISTS `livraisons`;
DROP TABLE IF EXISTS `commandes`;
DROP TABLE IF EXISTS `mouvements_stock`;
DROP TABLE IF EXISTS `numeros_serie`;
DROP TABLE IF EXISTS `lots`;
DROP TABLE IF EXISTS `regles_reapprovisionnement`;
DROP TABLE IF EXISTS `emplacements`;
DROP TABLE IF EXISTS `entrepots`;
DROP TABLE IF EXISTS `unites_mesure`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `fournisseurs`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `utilisateurs`;
DROP TABLE IF EXISTS `roles`;
SET FOREIGN_KEY_CHECKS = 1;
